// Generated 08-dec-2021
export const resultsCache = {
  "javascript bcrypt match passwords site:stackoverflow.com": [
    {
      title: "Compare passwords BcryptJS - Stack Overflow",
      snippet:
        "Compare passwords BcryptJS · javascript node.js express bcrypt. So I'm trying to build a very basic user login. I'm trying ...",
      url: "https://stackoverflow.com/questions/40076638/compare-passwords-bcryptjs",
    },
    {
      title: "how to compare bcrypt hash password - Stack Overflow",
      snippet:
        "bcrypt has a built-in method for comparing hashes. async function passCheck(event) { var fromDB = await pool.query('SELECT password from ...",
      url: "https://stackoverflow.com/questions/65920404/how-to-compare-bcrypt-hash-password",
    },
    {
      title: "nodejs - how to compare two hashes password of bcrypt",
      snippet:
        "I have these 2 hash password that came from the same password in bcrypt: var password = E@Js#07Do=U$ var hash1 = $2a$10$ ...",
      url: "https://stackoverflow.com/questions/55801772/nodejs-how-to-compare-two-hashes-password-of-bcrypt",
    },
    {
      title: "How does node.bcrypt.js compare hashed and plaintext ...",
      snippet:
        "Bcrypt compare hashed and plaintext passwords without the salt string because the hashed password contains the salt string which we created at ...",
      url: "https://stackoverflow.com/questions/13023361/how-does-node-bcrypt-js-compare-hashed-and-plaintext-passwords-without-the-salt",
    },
    {
      title: "Bcrypt password fails when i try to compare? - Stack Overflow",
      snippet:
        "node.js bcrypt ... I am using bcrypt to compare the hashed password with the original string but i am getting false statement.",
      url: "https://stackoverflow.com/questions/66134693/bcrypt-password-fails-when-i-try-to-compare",
    },
    {
      title: "Nodejs : in bcrypt it returns false at compare password hash",
      snippet:
        "When you compare() , you need to pass in the plaintext value as the first argument and the hash from your database as the second argument.",
      url: "https://stackoverflow.com/questions/24583608/nodejs-in-bcrypt-it-returns-false-at-compare-password-hash",
    },
    {
      title: "bcryptjs compare function returns false when passwords ...",
      snippet:
        "In the users.js file at the comparePassword function inside the compare method of bcrypt you are throwing the error instead of passing it to ...",
      url: "https://stackoverflow.com/questions/63408204/bcryptjs-compare-function-returns-false-when-passwords-contain-numbers",
    },
    {
      title: "Bcrypt-NodeJS compare() returns false whatever the password",
      snippet:
        "I know the solution has been found but just in case you are landing here out of google search and have the same issue, especially if you are ...",
      url: "https://stackoverflow.com/questions/46022956/bcrypt-nodejs-compare-returns-false-whatever-the-password/50537073",
    },
    {
      title: "Why am I getting isMatch null from bcrypt compare even ...",
      snippet:
        "When the user signup you save the hashed version of it not the actual text. const password = req.body.password // This hasedPassword will be ...",
      url: "https://stackoverflow.com/questions/66532228/why-am-i-getting-ismatch-null-from-bcrypt-compare-even-though-two-password-strin",
    },
    {
      title:
        "bcrypt-nodejs compare method returns false every time - Stack ...",
      snippet:
        "You appear to be passing in a string 'user.login.local.password' instead of the actual password in your userSchema pre save function: e.g. this ...",
      url: "https://stackoverflow.com/questions/30494856/bcrypt-nodejs-compare-method-returns-false-every-time",
    },
  ],
  "javascript jszip add html file JSZip generateAsync site:stackoverflow.com": [
    {
      title: "How to Zip files using jszip library - Stack Overflow",
      snippet:
        "Just keep calling zip.file() . Look at the example from their documentation page (comments mine): var zip = new JSZip(); // Add a text file ...",
      url: "https://stackoverflow.com/questions/17986432/how-to-zip-files-using-jszip-library",
    },
    {
      title: "How to Zip files using JavaScript? - Stack Overflow",
      snippet:
        "6 Answers · Extract the zip and find jszip.js file inside dist folder · Import jszip.js file in your html file like below · Add below function in your code and ...",
      url: "https://stackoverflow.com/questions/8608724/how-to-zip-files-using-javascript",
    },
    {
      title: "Need a JavaScript Simple Code For Zip A Folder - Stack ...",
      snippet:
        "I tried the jszip.js and zip.js but didnt work.why i dont know.. Here is the code: <html> <head> ...",
      url: "https://stackoverflow.com/questions/62300627/need-a-javascript-simple-code-for-zip-a-folder",
    },
    {
      title:
        "Zip Generated by JSZip contains only single image file - Stack ...",
      snippet:
        "Its quite simple. JSZipUtils.getBinaryContent calls a callback inside which you are appending filesto zip . And since callbacks don't run in ...",
      url: "https://stackoverflow.com/questions/58619118/zip-generated-by-jszip-contains-only-single-image-file",
    },
    {
      title: "Saving images from URL using JSzip - Stack Overflow",
      snippet:
        "I'm using JSzip to download the html of a div. The div has images inside of it (they're not base64 encoded). Is there a way I can use JSzip to ...",
      url: "https://stackoverflow.com/questions/26635627/saving-images-from-url-using-jszip",
    },
    {
      title: "Progress callback not updating during progress - Stack Overflow",
      snippet:
        'JavaScript execution and page rendering are done in the same ... var zip = new JSZip(); zip.file("myfile.txt", this.files[0]); statusEl.',
      url: "https://stackoverflow.com/questions/63246487/progress-callback-not-updating-during-progress",
    },
    {
      title: "Hottest 'jszip' Answers - Stack Overflow",
      snippet:
        "Extracting zipped files using JSZIP in javascript ... is not defined when using JSzip. It works after adding the following script tag in the HTML <script ...",
      url: "https://stackoverflow.com/tags/jszip/hot?filter=all",
    },
    {
      title: 'JSzip "generateAsync" not working on Internet Explorer?',
      snippet:
        'I want to download and save a collection of PDFs in a single ZIP file using "JSZip" ver. 3.2.1 and "FileSaver" of 24-Jan-2014 working with ...',
      url: "https://stackoverflow.com/questions/57976108/jszip-generateasync-not-working-on-internet-explorer",
    },
    {
      title:
        "I have to different zip files created using JSZip. Is is possible to ...",
      snippet:
        'stuk.github.io/jszip/documentation/howto/read_zip.html. See: "In node Js" the comment // read a file and add it to a zip. You need to call file ...',
      url: "https://stackoverflow.com/questions/57513029/i-have-to-different-zip-files-created-using-jszip-is-is-possible-to-combile-the",
    },
    {
      title: "saveAs is not defined when using JSzip - Stack Overflow",
      snippet:
        "There is a comment in their example: // see FileSaver.js. You need that module if you want to use saveAs().",
      url: "https://stackoverflow.com/questions/41704748/saveas-is-not-defined-when-using-jszip",
    },
  ],
  "javascript mongodb find less than site:stackoverflow.com": [
    {
      title: "NodeJS + MongoDB: find() where { 'value' : < 5 AND >1}",
      snippet:
        "It's a simple string, containing UNIX time of the last call. I'd like to find all the companies, where lastcall is higher than a AND lower than ...",
      url: "https://stackoverflow.com/questions/11069417/nodejs-mongodb-find-where-value-5-and-1-how",
    },
    {
      title: "How to use a less than comparison within a mongo find ...",
      snippet:
        "Assuming LastUpdateTime is a timestamp, something like this should work: const twoHoursAgo = Date.now() - (1000 * 60 * 60 * 2); const ...",
      url: "https://stackoverflow.com/questions/67320987/how-to-use-a-less-than-comparison-within-a-mongo-find-javascript",
    },
    {
      title: "MongoDB - find result where value is null or less than X",
      snippet:
        "You are looking for the $or operation, which accepts an array of operations. It would be like so: $or: [{end_date: null}, {end_date: {$gte: ...",
      url: "https://stackoverflow.com/questions/18342529/mongodb-find-result-where-value-is-null-or-less-than-x",
    },
    {
      title: "mongodb find where field lower than another field plus ...",
      snippet:
        "I want to have a find() query that returns the documents in this collection where 'warehouseStock' is less than ('reservedStock' + threshold), ...",
      url: "https://stackoverflow.com/questions/43306657/mongodb-find-where-field-lower-than-another-field-plus-parameter-value",
    },
    {
      title: "Query date less than today in mongodb - Stack Overflow",
      snippet:
        "I'd like to count how many data is durationEnd date is less than today date. From the data above I know I have one. Using nodejs I have tried with the below ...",
      url: "https://stackoverflow.com/questions/27633480/query-date-less-than-today-in-mongodb",
    },
    {
      title: "Query MongoDb for a datetime value less than NOW - Stack ...",
      snippet:
        "Use the Javascript function new Date() : db.collection.find({ Expiration: { $lte: new Date() } }). The Mongo shell is just a Javascript ...",
      url: "https://stackoverflow.com/questions/29791171/query-mongodb-for-a-datetime-value-less-than-now",
    },
    {
      title: "Mongoose greater than and equal - Stack Overflow",
      snippet:
        "$gte selects the documents where the value of the field is greater than or equal to (i.e. >=) a specified value query.find( { marks: { $gte: ...",
      url: "https://stackoverflow.com/questions/50043003/mongoose-greater-than-and-equal/50043155",
    },
    {
      title: "NodeJS MongoDB Find posts that are older than current date",
      snippet:
        "You can subtract one hour from the moment using .subtract function and then use $gte operator to obtain only the greater values/documents ...",
      url: "https://stackoverflow.com/questions/54890174/nodejs-mongodb-find-posts-that-are-older-than-current-date",
    },
    {
      title: "How to find documents where field1 is greater than field2 ...",
      snippet:
        "How to find documents where field1 is greater than field2? ( Nodejs/Mongoose/MongoDB) · node.js mongodb mongoose nosql. How do you use values from fields in ...",
      url: "https://stackoverflow.com/questions/31206795/how-to-find-documents-where-field1-is-greater-than-field2-nodejs-mongoose-mon",
    },
    {
      title: "check the condition if the values are less then or equal or ...",
      snippet:
        "This query answers in the question : user enters 1 or 2 saved in a application variable lets say var=parameter; if he entered 1 => i want ...",
      url: "https://stackoverflow.com/questions/69285429/check-the-condition-if-the-values-are-less-then-or-equal-or-greater-than-mongodb",
    },
  ],
  "javascript mongodb findOneAndUpdate return updated document site:stackoverflow.com":
    [
      {
        title: "findOneAndUpdate doesn't return updated document - Stack ...",
        snippet:
          "Why this happens? The default is to return the original, unaltered document. If you want the new, updated document to be returned you have ...",
        url: "https://stackoverflow.com/questions/32811510/mongoose-findoneandupdate-doesnt-return-updated-document",
      },
      {
        title: "How to get updated document back from the ...",
        snippet:
          "The Node.js driver documentation doesn't mention a returnNewDocument option for findOneAndUpdate() (which is an option for the MongoDB shell ...",
        url: "https://stackoverflow.com/questions/35626040/how-to-get-updated-document-back-from-the-findoneandupdate-method",
      },
      {
        title: "db.collection.findOneAndUpdate () is not returning the ...",
        snippet:
          "Always check the Node JS MongoDB API ... For mongoose to return the new document, you need to add { new: true } to the query.",
        url: "https://stackoverflow.com/questions/64941311/db-collection-findoneandupdate-is-not-returning-the-updated-document",
      },
      {
        title: "Update And Return Document In Mongodb - Stack Overflow",
        snippet:
          "Update And Return Document In Mongodb · node.js mongodb. I want to get updated documents. This is my original code and it successfully updates ...",
        url: "https://stackoverflow.com/questions/24747189/update-and-return-document-in-mongodb",
      },
      {
        title: "Return updated collection with Mongoose - Stack Overflow",
        snippet:
          'use findOneAndUpdate() method and in query parameter use option as { "new": true} return this.sessionModel .findOneAndUpdate({user_id: ...',
        url: "https://stackoverflow.com/questions/20667739/return-updated-collection-with-mongoose/42385630",
      },
      {
        title: "mongoose findOneAndUpdate returns updated document but ...",
        snippet:
          "Mongoose can only update the table with the defined fields in schema. So, if the processed field does not exist in Mongoose schema, it won't ...",
        url: "https://stackoverflow.com/questions/48545733/mongoose-findoneandupdate-returns-updated-document-but-doesnt-update-database",
      },
      {
        title: "Update multiple documents and return all updated documents",
        snippet:
          "In Mongoose, the findOneAndUpdate() is based on the native findAndModify() method of MongoDB. If you check the offical documentation of the ...",
        url: "https://stackoverflow.com/questions/42246188/update-multiple-documents-and-return-all-updated-documents",
      },
      {
        title: "How can I return an updated document from mongodb ...",
        snippet:
          "Use the {new: true} option. User.findOneAndUpdate({ email: userEmail }, { $set: { resetPasswordToken: token, resetPasswordExpires: now } } ...",
        url: "https://stackoverflow.com/questions/62475673/how-can-i-return-an-updated-document-from-mongodb-mongoose",
      },
      {
        title: "Get the updated document in MongoDB - Stack Overflow",
        snippet:
          "In nodejs API solution is to set: {returnOriginal: false}. collection.findOneAndUpdate( whereObj, updateObj, {returnOriginal: false});.",
        url: "https://stackoverflow.com/questions/16333343/get-the-updated-document-in-mongodb",
      },
      {
        title: "Document not updated in findOneAndUpdate - Stack Overflow",
        snippet:
          "It matters what schema you use to query database. Discriminators build the mongo queries based on the object you use.",
        url: "https://stackoverflow.com/questions/54892850/document-not-updated-in-findoneandupdate",
      },
    ],
  "javascript axios cancel post request site:stackoverflow.com": [
    {
      title: "how to cancel/abort ajax request in axios - Stack Overflow",
      snippet:
        "Axios does not support canceling requests at the moment. Please see this issue for details. UPDATE: Cancellation support was added in axios ...",
      url: "https://stackoverflow.com/questions/38329209/how-to-cancel-abort-ajax-request-in-axios",
    },
    {
      title: "Canceling my promises a POST Request through axios in ...",
      snippet:
        "If you use axios this can be done by using a cancel token: axios.isCancel(thrown).",
      url: "https://stackoverflow.com/questions/63422796/canceling-my-promises-a-post-request-through-axios-in-reactjs",
    },
    {
      title: "Cant cancel Axios post request via CancelToken - Stack ...",
      snippet:
        "In previous code,i have passed cancelToken to the POST data request not as a axios setting. import axios from 'axios' var CancelToken = axios.",
      url: "https://stackoverflow.com/questions/44852054/cant-cancel-axios-post-request-via-canceltoken",
    },
    {
      title: "Cancel axios get request when typing reactjs - Stack Overflow",
      snippet:
        "Since axios v0.15 you can cancel request: You can also create a cancel token by passing an executor function to the CancelToken constructor:.",
      url: "https://stackoverflow.com/questions/42896831/cancel-axios-get-request-when-typing-reactjs",
    },
    {
      title: "Cancelling previous API requests with Axios - Stack Overflow",
      snippet:
        "I am trying to follow Axios documentation to cancel repeated requests to an URL but while I get no errors the requests aren't being cancelled. I ...",
      url: "https://stackoverflow.com/questions/57382537/cancelling-previous-api-requests-with-axios",
    },
    {
      title: "Cancel File Upload Post request using Axios - Stack Overflow",
      snippet:
        "You need to make use of CancelToken . Basically, you need to pass a canceltoken in the config object while using axios.post and when you ...",
      url: "https://stackoverflow.com/questions/55051917/cancel-file-upload-post-request-using-axios",
    },
    {
      title: "Cancel previous request using axios with vue.js - Stack Overflow",
      snippet:
        "2020 UPDATE: How to cancel an axios request. generate a cancelToken and store it. import axios from 'axios' const request = axios.",
      url: "https://stackoverflow.com/questions/50516438/cancel-previous-request-using-axios-with-vue-js",
    },
    {
      title:
        "Cancel previous post requests by using axios ... - Stack Overflow",
      snippet:
        "Cancel previous post requests by using axios and axios cancel token · javascript react-native axios. I'm using a post request to retrieve some ...",
      url: "https://stackoverflow.com/questions/61198475/cancel-previous-post-requests-by-using-axios-and-axios-cancel-token",
    },
    {
      title: "Cancel Axios post request outside useEffect hook - Stack ...",
      snippet:
        "This is because you're losing the changes between renders. During the handleCreate call the variable changes only for that render.",
      url: "https://stackoverflow.com/questions/57463256/cancel-axios-post-request-outside-useeffect-hook",
    },
    {
      title: "Not working on cancellation of POST in Axios - Stack Overflow",
      snippet:
        "I faced the same issue with a get request. You need to pass headers in axios properties. axios.get(url, { cancelToken: ..., headers: { .",
      url: "https://stackoverflow.com/questions/51380394/not-working-on-cancellation-of-post-in-axios",
    },
  ],
};
